name: 🔧 HTML CI Pipeline

on:
  push:
    branches:
      - main
      - production

jobs:
  run-basic-ci:
    name: Run Basic CI Check
    runs-on: ubuntu-latest

    steps:
      - name: 👋 Print Hello Message
        run: echo "✅ Hello from GitHub Actions - HTML CI Pipeline!"

      - name: 🕒 Print Current Date and Time
        run: date
        